version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3333:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql